# Generated by Django 5.1.3 on 2025-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(max_length=255)),
                ('Number_of_guest', models.IntegerField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('DateTime_of_booking', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
