# Generated by Django 5.1.1 on 2025-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='100')),
                ('number_of_guest', models.IntegerField()),
                ('description', models.TextField(default='No description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
