# Generated by Django 5.1.1 on 2025-01-25 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 12)),
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default='hvh@gmail.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='user/profile_image/default.jpg', upload_to='user/profile_image'),
        ),
    ]
